// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthResponse struct {
	Token *string `json:"token,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	Username     string `json:"username"`
	Passwordhash string `json:"passwordhash"`
}

type UserData struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
